"""Added job hazard analysis task, hazard, and consequences

Revision ID: 2abb5e934322
Revises: f6a62ad846a7
Create Date: 2024-04-21 16:32:47.280743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abb5e934322'
down_revision = 'f6a62ad846a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_hazard_analysis_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_hazard_analysis_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_hazard_analysis_id'], ['job_hazard_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_hazard_analysis_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_hazard_analysis_task_job_hazard_analysis_id'), ['job_hazard_analysis_id'], unique=False)

    op.create_table('job_hazard_analysis_task_hazard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_harazrd_analysis_task_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_harazrd_analysis_task_id'], ['job_hazard_analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_hazard_analysis_task_hazard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_hazard_analysis_task_hazard_job_harazrd_analysis_task_id'), ['job_harazrd_analysis_task_id'], unique=False)

    op.create_table('job_hazard_analysis_task_consequence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_harazrd_analysis_task_hazard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_harazrd_analysis_task_hazard_id'], ['job_hazard_analysis_task_hazard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_hazard_analysis_task_consequence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_hazard_analysis_task_consequence_job_harazrd_analysis_task_hazard_id'), ['job_harazrd_analysis_task_hazard_id'], unique=False)

    with op.batch_alter_table('job_hazard_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_hazard_analysis', schema=None) as batch_op:
        batch_op.drop_column('author')
        batch_op.drop_column('title')

    with op.batch_alter_table('job_hazard_analysis_task_consequence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_hazard_analysis_task_consequence_job_harazrd_analysis_task_hazard_id'))

    op.drop_table('job_hazard_analysis_task_consequence')
    with op.batch_alter_table('job_hazard_analysis_task_hazard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_hazard_analysis_task_hazard_job_harazrd_analysis_task_id'))

    op.drop_table('job_hazard_analysis_task_hazard')
    with op.batch_alter_table('job_hazard_analysis_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_hazard_analysis_task_job_hazard_analysis_id'))

    op.drop_table('job_hazard_analysis_task')
    # ### end Alembic commands ###
