"""make preventative measure many to one with hazard

Revision ID: 69624dbc8510
Revises: 90c83e2d3f37
Create Date: 2024-04-21 20:14:04.317407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69624dbc8510'
down_revision = '90c83e2d3f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_hazard_analysis_task_consequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_hazard_analysis_task_hazard_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_job_hazard_analysis_task_consequence_job_harazrd_ana_2630')
        batch_op.create_index(batch_op.f('ix_job_hazard_analysis_task_consequence_job_hazard_analysis_task_hazard_id'), ['job_hazard_analysis_task_hazard_id'], unique=False)
        batch_op.drop_constraint('job_hazard_analysis_task_cons_job_harazrd_analysis_task_ha_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job_hazard_analysis_task_hazard', ['job_hazard_analysis_task_hazard_id'], ['id'])
        batch_op.drop_column('job_harazrd_analysis_task_hazard_id')

    with op.batch_alter_table('job_hazard_analysis_task_hazard_preventative_measure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_hazard_analysis_task_hazard_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_job_hazard_analysis_task_hazard_preventative_measure_2ab0')
        batch_op.create_index(batch_op.f('ix_job_hazard_analysis_task_hazard_preventative_measure_job_hazard_analysis_task_hazard_id'), ['job_hazard_analysis_task_hazard_id'], unique=False)
        batch_op.drop_constraint('job_hazard_analysis_task_haza_job_harazrd_analysis_task_ha_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job_hazard_analysis_task_hazard', ['job_hazard_analysis_task_hazard_id'], ['id'])
        batch_op.drop_column('job_harazrd_analysis_task_hazard_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_hazard_analysis_task_hazard_preventative_measure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_harazrd_analysis_task_hazard_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_hazard_analysis_task_haza_job_harazrd_analysis_task_ha_fkey', 'job_hazard_analysis_task_hazard', ['job_harazrd_analysis_task_hazard_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_job_hazard_analysis_task_hazard_preventative_measure_job_hazard_analysis_task_hazard_id'))
        batch_op.create_index('ix_job_hazard_analysis_task_hazard_preventative_measure_2ab0', ['job_harazrd_analysis_task_hazard_id'], unique=False)
        batch_op.drop_column('job_hazard_analysis_task_hazard_id')

    with op.batch_alter_table('job_hazard_analysis_task_consequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_harazrd_analysis_task_hazard_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_hazard_analysis_task_cons_job_harazrd_analysis_task_ha_fkey', 'job_hazard_analysis_task_hazard', ['job_harazrd_analysis_task_hazard_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_job_hazard_analysis_task_consequence_job_hazard_analysis_task_hazard_id'))
        batch_op.create_index('ix_job_hazard_analysis_task_consequence_job_harazrd_ana_2630', ['job_harazrd_analysis_task_hazard_id'], unique=False)
        batch_op.drop_column('job_hazard_analysis_task_hazard_id')

    # ### end Alembic commands ###
