"""get rid of step

Revision ID: 944bf36812cc
Revises: 39f74b0ad8bd
Create Date: 2024-04-22 13:56:20.222863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944bf36812cc'
down_revision = '39f74b0ad8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_hazard_analysis_task', schema=None) as batch_op:
        batch_op.drop_column('step')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_hazard_analysis_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
