"""Added job hazard analysis consequence description

Revision ID: c1c7c735c18c
Revises: 2abb5e934322
Create Date: 2024-04-21 16:34:17.499127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c7c735c18c'
down_revision = '2abb5e934322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_hazard_analysis_task_consequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_hazard_analysis_task_consequence', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
