"""add createdutc and updatedutc to models

Revision ID: ed2d5100f889
Revises: 69624dbc8510
Create Date: 2024-04-21 20:49:32.750136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2d5100f889'
down_revision = '69624dbc8510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_hazard_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_utc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_utc', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_hazard_analysis_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_utc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_utc', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_hazard_analysis_task_consequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_utc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_utc', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_hazard_analysis_task_hazard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_utc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_utc', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_hazard_analysis_task_hazard_preventative_measure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_utc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_utc', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_hazard_analysis_task_hazard_preventative_measure', schema=None) as batch_op:
        batch_op.drop_column('updated_utc')
        batch_op.drop_column('created_utc')

    with op.batch_alter_table('job_hazard_analysis_task_hazard', schema=None) as batch_op:
        batch_op.drop_column('updated_utc')
        batch_op.drop_column('created_utc')

    with op.batch_alter_table('job_hazard_analysis_task_consequence', schema=None) as batch_op:
        batch_op.drop_column('updated_utc')
        batch_op.drop_column('created_utc')

    with op.batch_alter_table('job_hazard_analysis_task', schema=None) as batch_op:
        batch_op.drop_column('updated_utc')
        batch_op.drop_column('created_utc')

    with op.batch_alter_table('job_hazard_analysis', schema=None) as batch_op:
        batch_op.drop_column('updated_utc')
        batch_op.drop_column('created_utc')

    # ### end Alembic commands ###
