"""Initial migration Job Hazard Analysis

Revision ID: f6a62ad846a7
Revises: 
Create Date: 2024-04-21 15:32:31.953276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a62ad846a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_hazard_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_hazard_analysis')
    # ### end Alembic commands ###
